package lf2.flap.controllers;

public enum Actions {
	ABOUT, AFD, AFND, REGEX, GAR, RA, EXIT ,
	VALIDATE,ADD_ALPHABET, ADD_V, SELECT_S, ADD_PRODUCT,ACCEPT, HOME, 
	PANEL_GRAMMAR, VALIDATE_LANGUAJE ;
}
